---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-collector-conf
  labels:
    app: opencensus
    component: oc-collector-conf
data:
  oc-collector-config: |
    log-level: DEBUG
    receivers:
      jaeger: {}
    exporters:
      opencensus:
        endpoint: "localforwarder:55678"
      jaeger:
        collector_endpoint: "http://jaeger-collector:14268/api/traces"
---
apiVersion: v1
kind: Service
metadata:
  name: oc-collector
  labels:
    app: opencesus
    component: oc-collector
spec:
  ports:
  - name: jaeger-thrift-http
    port: 14268    
  selector:
    component: oc-collector
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oc-collector
  labels:
    app: opencensus
    component: oc-collector
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
#      annotations:
#        prometheus.io/path: "/metrics"
#        prometheus.io/port: "8888"
#        prometheus.io/scrape: "true"
      labels:
        app: opencensus
        component: oc-collector
    spec:
      containers:
      - image: omnition/opencensus-collector:0.1.5
        name: oc-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        command:
          - "/occollector_linux"
          - "--config=/conf/oc-collector-config.yaml"
        ports:
#        - containerPort: 55678
        - containerPort: 14267
        - containerPort: 14268          
#        - containerPort: 9411
        volumeMounts:
        - name: oc-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
      volumes:
        - configMap:
            name: oc-collector-conf
            items:
              - key: oc-collector-config
                path: oc-collector-config.yaml
          name: oc-collector-config-vol